version: '3.9'

services:
  game_service:
    restart: always
    image: ${SERVER_IMAGE}
    environment:
      DB_HOST: dbsql-server
      DB_PORT: 5432
      DB_USER: gorm
      DB_PASS: /run/secrets/db_password
      DB_NAME: game_db
    networks:
      - game_app_network
    links:
      - db:dbsql-server
    ports:
      - "8080:8080"
  db:
    restart: always
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: game_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/va/lib/postgresql/data/pgdata
    networks:
      - game_app_network
    ports:
      - "5432:5432"
  pgadmin:
    restart: always
    image: dpage/pgadmin4:7.0
    environment:
      PGADMIN_DEFAULT_EMAIL: amobe.momoko@gmail.com
      PGADMIN_DEFAULT_PASSWORD: /run/secrets/pgadmin_password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "28080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - game_app_network
    links:
      - db:dbsql-server
networks:
  game_app_network:
    name: game_app_network
    driver: bridge
volumes:
  db-data:
  pgadmin-data:
secrets:
  db_password:
    file: ./secrets/db_password.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
