apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: prod
resources:
  - ../../base
patchesStrategicMerge:
  - hpa.yaml
secretGenerator:
  - name: service-env
    envs:
      - .env
