apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playgame-ingress
  annotations:
    cert-manager.io/issuer: playgame-issuer
spec:
  tls:
    - hosts: [] # hosts will be added in another patch
      secretName: playgame-cert
  rules:
    - host: [] # hosts will be added in another patch
