apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/playgame

namespace: playgame

patchesStrategicMerge:
  - ingress.yaml

patchesJson6902:
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: playgame-ingress

configurations:
  - cert-manager-configuration.yaml
