apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: playgame
  demo: kustomize-cert-manager

namespace: playgame

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml

secretGenerator:
  - name: service-env
    envs:
      - .env

