apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: playgame-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: # email will be added in another patch
    privateKeySecretRef:
      name: issuer-letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            name: playgame-ingress
