apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../playgame-cert
  - issuer.yaml

namespace: playgame

commonLabels:
  app: playgame
  demo: kustomize-cert-manager

patches:
  - path: issuer-patch.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: Issuer
      name: playgame-issuer
